---
host: 0.0.0.0
port: 5000
db_path: '/db'
get_states: true
run_rules: false
periodic_work_assignment_interval: 300
get_zombie_screenshot_interval: 300
retry_rule_interval: 60
update_state_interval: 60
pending_work_interval: 10
pending_work_timeout: 30
become_zombie_interval: 120
mark_zombie_interval: 10
check_work_interval: 1
max_parallel_work: 3
pause_between_keys: 5
