name: publish image

on:
  push:
    tags:
      - "v*.*"

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:

    - name: generate tags
      run: echo "::set-output name=tags::rebooto/${{ github.event.repository.name }}:${REF_NAME:1},rebooto/${{ github.event.repository.name }}:latest"
      id: gen_tags
      env:
        REF_NAME: ${{ github.ref_name }}

    - name: checkout
      uses: actions/checkout@v2

    - name: Update version number
      run: sed -i 's?DEV-VERSION-0.0?${{ github.ref_name }}?' app/version.py

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: rebooto
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.gen_tags.outputs.tags }}
